# Generated by Django 5.0.1 on 2024-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='routing_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='swift_bic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
