# Generated by Django 5.0.1 on 2024-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bankuser_alter_userbankrelationship_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='banks',
            field=models.ManyToManyField(through='api.UserBankRelationship', to='api.bank'),
        ),
    ]
