version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
  node_modules: